### PR TITLE
Simplified Chinese translation

### PR DESCRIPTION
**Pull request by brynne8**
I created the Simplified Chinese translation for the tool. Please merge it, thanks.

### CODE REVIEW

**Comment by Taiwania** [comment]
@FDMS, the ISO code filename of Simplified Chinese is `zh-hans.php`.

**Comment by Taiwania** [comment]
@AlexanderMisel, Line 251 `创用CC 姓名标示-相同方式分享 4.0 国际版（CC BY-SA 4.0）` should be `知识共享 署名-相同方式分享 4.0 国际版（CC BY-SA 4.0）`.

**Comment by brynne8** [comment]
I corrected the translation.

**Comment by FDMS** [comment]
Thanks; now live at http://tools.wmflabs.org/relgen/i18n/zh-hans.php.

**Pull request merged**
